[project]
name = "recurrence"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rasterio>=1.4.1",
    "statsmodels>=0.14.4",
]
